### ISSUE TITLE
Typo error and missing region

### ISSUE THREAD

**Issue by Jovin-Ang** [ickerio/pubg.js#14]
look at GameModeStats.js line 185
```this.bestRankPoints = content.bestRankPoints;```
its supposed to be `bestRankPoint`
without the s

New region `xbox-sa` is missing too.

**Comment by ickerio** [comment]
Thanks, and sorry for the late reply.
Fixed here b86ecc8e94416e63c301beebd09e8069471baccd and here 39b15ba2c1f56f08d5a2a3f2b444e864385f037e
