### ISSUE TITLE
Lodash 

### ISSUE THREAD

**Issue by ickerio** [ickerio/pubg.js#20]
Ewww yuck. @Zaytt how necessary is this package? I've always disliked it as in my opinion it's so unnecessary and just bloats the the overall package. Would it be possible to implement your own version of these functions and have them in Util.js?

eg `omit` could be replaced with an easy ES6 filter function

**Comment by Zaytt** [comment]
lodash? I used mostly for the merge function. I agree the omit can be implemented with one of my own. I also believe lodash allows imports for single functions, like: 
https://www.npmjs.com/package/lodash.omit
https://www.npmjs.com/package/lodash.merge

Would that be ok with you?

**Comment by Zaytt** [comment]
I just did what I wrote above. Now only lodash.merge and lodash.omit are required. It was indeed unnecessary to import the whole library

**Comment by ickerio** [comment]
Great, thanks v much.  👍
