### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by dialogik** [ickerio/pubg.js#39]
I am recently getting errors due to missing `id`s. This is most likely caused by erroneous API responses, where Match `id`s are missing ([see this Tweet for more information](https://twitter.com/dialogikTV/status/1403645659656425478) as well)

![image](https://user-images.githubusercontent.com/1260548/125260839-03040680-e301-11eb-823c-71b3e914dccf.png)

This causes the pubg.js library to fail since it requires the Match `id`.

![image](https://user-images.githubusercontent.com/1260548/125261087-3d6da380-e301-11eb-998f-a1dea5377f46.png)

There should be a workaround checking if `id` is present and skip that row if there is no `id` present.

**Comment by ickerio** [comment]
Hi, I no longer maintain this library. If you'd like to make a pull request to fix this I'll gladly accept it though. Cheers!

**Comment by dialogik** [comment]
See #40
